module.exports = [
    {"address":"634 Johnson Court",
    "realEstate":"Keebler LLC",
    "linkURL":"utexas.edu",
    "rooms":1,
    "bathrooms":1,
    "extras":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    "petFriendly":false,
    "rentPrice":"$450.60",
    "FinalComments": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "imageURL":"http://dummyimage.com/600x600.png/5fa2dd/ffffff"},

    {"address":"47665 Johnson Point",
    "realEstate":"Schamberger, Bednar and Runte",
    "linkURL":"qq.com",
    "rooms":3,
    "bathrooms":2,
    "extras":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    "petFriendly":true,
    "rentPrice":"$582.87",
    "FinalComments": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "imageURL":"http://dummyimage.com/600x600.png/dddddd/000000"},


    {"address":"22 Merrick Park",
    "realEstate":"Yundt-Cummings",
    "linkURL":"lycos.com",
    "rooms":4,
    "bathrooms":2,
    "extras":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    "petFriendly":true,
    "rentPrice":"$371.89",
    "FinalComments": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "imageURL":"http://dummyimage.com/600x600.png/dddddd/000000"},

    {"address":"3 Basil Way",
    "realEstate":"Ratke, Bode and Blick",
    "linkURL":"telegraph.co.uk",
    "rooms":4,
    "bathrooms":3,
    "extras":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    "petFriendly":false,
    "rentPrice":"$629.41",
    "Final Comments": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "imageURL":"http://dummyimage.com/600x600.png/ff4444/ffffff"},

    {"address":"378 Schurz Terrace",
    "realEstate":"Lindgren, Thompson and Kuhn",
    "linkURL":"gizmodo.com",
    "rooms":5,
    "bathrooms":2,
    "extras":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    "petFriendly":true,
    "rentPrice":"$363.09",
    "FinalComments": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "imageURL":"http://dummyimage.com/600x600.png/dddddd/000000"},

    {"address":"59 Bonner Way",
    "realEstate":"Mayer-Kunde",
    "linkURL":"squidoo.com",
    "rooms":5,
    "bathrooms":3,
    "extras":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    "petFriendly":false,
    "rentPrice":"$585.60",
    "FinalComments": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "imageURL":"http://dummyimage.com/600x600.png/5fa2dd/ffffff"}
]